# Generated by Django 5.1.4 on 2024-12-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_llms_alter_agent_usecases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='url',
        ),
    ]
