# Generated by Django 5.1.4 on 2024-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agent_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='llms',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agents.agentllm'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='usecases',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agents.usecase'),
        ),
    ]
