# Generated by Django 5.1.4 on 2024-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agentresponse_agent_alter_agentresponse_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresponse',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
