# Generated by Django 5.1.4 on 2024-12-14 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentresponse_completed_at_agentresponse_output'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentresponse',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['name', 'is_active'], name='agents_agen_name_2a7935_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['-created_at'], name='agents_agen_created_8ad106_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinput',
            index=models.Index(fields=['agent', 'input_type'], name='agents_agen_agent_i_d7add4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentresponse',
            index=models.Index(fields=['user', '-started_at'], name='agents_agen_user_id_a0301e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentresponse',
            index=models.Index(fields=['agent', 'status'], name='agents_agen_agent_i_2fb039_idx'),
        ),
    ]
